tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap "homebrew/bundle"
tap "homebrew/core"

# Binaries
brew "coreutils"
brew "fzf"
brew "gh"
brew "go"
brew "httpie"
brew "jq"
brew "python"
brew "thefuck"
brew "tree"
brew "unar"
brew "wget"
brew "kubectl"
brew "kubectx"

# Apps
cask 'discord'
cask 'rancher' # Replacement for Docker Desktop
cask 'gpg-suite'
cask 'insomnia' # HTTP client
cask 'maccy' # Copy history
cask 'visual-studio-code' # Coding
cask "rectangle" # Window manager
cask 'protonmail-bridge'
cask 'spotify' # Music 🎶
cask 'warp' # Terminal
brew 'mac-mouse-fix' # MacOS mouse fix

