tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap "homebrew/bundle"
tap "homebrew/core"

# Binaries
brew "antibody"
brew "coreutils"
brew "fzf"
brew "gh"
brew "go"
brew "httpie"
brew "jq"
brew "python"
brew "thefuck"
brew "tree"
brew "unar"
brew "wget"
brew "kubectl"
brew "kubectx"

# Apps
cask '1password'
cask 'discord'
cask 'rancher' # Replacement for Docker Desktop
cask 'gpg-suite'
cask 'insomnia' # HTTP client
cask 'maccy' # Copy history
cask 'signal' # Messaging app
cask 'visual-studio-code' # Coding
cask 'tableplus' # Database client
cask "rectangle" # Window manager
cask 'protonmail-bridge'
cask 'protonvpn'
cask 'spotify' # Music 🎶
cask 'warp' # Terminal
cask 'google-chrome'
cask 'microsoft-edge'
cask 'google-cloud-sdk'
